components/app/Comment.tsx
components/atoms/Button.tsx
components/atoms/DetailButton.tsx
components/atoms/FileUploader.tsx
components/atoms/Input.tsx
components/atoms/LabelForm.tsx
components/atoms/ModalButton.tsx
components/atoms/Radio.tsx
components/atoms/Textarea.tsx
components/common/Header/UploadModal/FileUploadView.tsx
components/common/Header/UploadModal/FormView.tsx
components/common/Header/UploadModal/Navigator.tsx
components/common/Header/UploadModal/SubmitView.tsx
components/common/Header/UploadModal/index.tsx
components/common/Header/index.tsx
components/common/Modal/View.tsx
components/common/Portfolio.tsx
components/common/SearchBar.tsx
components/main/PortfolioList.tsx
components/portfolio/Description.tsx
e2e/tests/index.spec.ts
fixtures/index.ts
tailwind.config.js

https://qkrjh0904.atlassian.net/browse/BSSMH-64
https://user-images.githubusercontent.com/80014454/211184300-b39812fe-574c-4ca3-9ed1-945419d4c7a7.mov
모달창의 마지막 제출부분 페이지를 추가하였습니다

모달 공개범위 선택 페이지 추가

---

.github/workflows/e2e-test.yaml
.github/workflows/lint.yaml
.github/workflows/unit-test.yaml
.gitignore
README.md
apis/httpClient.ts
apis/index.ts
components/app/Detail.tsx
components/app/PortfolioPlayer.tsx
components/common/Portfolio.tsx
components/index.ts
components/main/PortfolioList.tsx
components/portfolio/SideMenuItem.tsx
config/const.ts
config/index.ts
fixtures/index.ts
models/portfolio/index.ts
next.config.js
package.json
pages/_app.tsx
pages/portfolio/[id].tsx
types/portfolio.interface.ts
utils/api.ts
utils/date.ts
utils/file.ts
yarn.lock

https://qkrjh0904.atlassian.net/browse/BSSMH-25
https://qkrjh0904.atlassian.net/browse/BSSMH-50
* 포트폴리오 동영상 보여주는 건 기능 추가 필요
README 보면 server url 설정 env 생겼으니 참고해서 .env 파일 만들고 사용하시면 됩니다

포트폴리오 목록, 조회 api 연결

---

components/app/PortfolioPlayer.tsx
components/app/SideMenuPortfolio.tsx

https://qkrjh0904.atlassian.net/browse/BSSMH-47
영상이 너무 커서 [여기](https://youtu.be/P8qxwVl1h14)에 업로드했습니다!
비디오 추가 이후 레이아웃이 깨지는 이슈가 있어서 수정하였습니다.

포트폴리오 개별조회 레이아웃 수정

---

components/common/SearchBar.tsx

https://qkrjh0904.atlassian.net/browse/BSSMH-91
https://user-images.githubusercontent.com/80014454/213969113-edde81d4-1aaf-4d47-91d7-2edbe8d85015.mov
x버튼이 생기면 search바의 width가 늘어나는 부분을 수정하였습니다.
‼️ 아래는 예전 화면입니다 ‼️

X 버튼이 생기면 검색바의 길이가 길어지는 부분 수정

---

components/app/CommentList.tsx
components/app/UploadModal/index.tsx
types/portfolio.interface.ts

* 포트폴리오 타입 추가
* 댓글 추가 후 내용 비우기

포트폴리오 타입 추가, 댓글 추가 후 내용 비우기

---

components/app/CommentList.tsx
components/app/UploadModal/index.tsx
components/common/Header/View.tsx
e2e/tests/index.spec.ts
hooks/useUser.ts
pages/mypage/index.tsx
types/portfolio.interface.ts

https://qkrjh0904.atlassian.net/browse/BSSMH-126
https://qkrjh0904.atlassian.net/browse/BSSMH-130
로그인 안했을 때 유저아이콘, 회원가입 버튼 삭제, 
mypage 접근 막기
포트폴리오 타입 입력 추가
댓글 추가후 내용 비우기

로그인 안했을 때 유저아이콘, 회원가입 버튼 삭제, mypage 접근 막기

---

components/common/Portfolio.tsx

(오른쪽이 에러난 이미지)
이미지 에러나면 test 이미지 노출

이미지 에러나면 test 이미지 노출

---

apis/httpClient.ts
components/atoms/SqureButton.tsx
components/contents/DataGrid.tsx
components/contents/DataGridItem.tsx
utils/date.ts

https://qkrjh0904.atlassian.net/browse/BSSMH-135
https://user-images.githubusercontent.com/80014454/220814399-c53012e7-b7a0-4507-8842-3a16edd7c881.mov
드래그로 포트폴리오 순서를 제어하는 기능을 추가했습니다

내 포트폴리오 순서 제어 추가

---

components/app/UploadModal/index.tsx
components/common/KebabMenu.tsx
models/key/index.ts
models/oauth/index.ts
models/portfolio/index.ts
models/search/index.ts
models/skill/index.ts

지라 이슈는 없습니다!
https://user-images.githubusercontent.com/80014454/220951449-9188f2bc-bf1a-4561-850c-68fa7b253220.mov
복잡한 구조 속 refetch를 위해 invalidateQueries를 도입했습니다.

invalidateQueries 추가

---

components/app/CommentList.tsx
components/app/Detail.tsx
components/app/PortfolioItem.tsx
components/app/PortfolioPlayer.tsx
components/app/UploadModal/index.tsx
components/atoms/CheckBox.tsx
components/atoms/Chip.tsx
components/atoms/Radio.tsx
components/common/Avatar.tsx
components/common/Logo.tsx
components/common/Portfolio.tsx
components/contents/DataGridItem.tsx
components/portfolio/edit/EditFileUploadView.tsx
hooks/useOverlay.ts
package.json
pages/portfolio/[portfolioId]/index.tsx
tailwind.config.js
yarn.lock

지라 이슈는 없습니다!
아래는 iframe 이슈 수정한 레이아웃입니다. (아직 디자인이 나오지 않아 추가만 해두었습니다!)
아래는 스크롤바 삭제한 영상입니다
https://user-images.githubusercontent.com/80014454/221355925-f3d89716-30f7-4328-ad9e-2e4fe5e7cad7.mov
* 업로드 모달의 Chip.Group의 레이아웃이 깨지는 문제를 수정하였습니다.
* Chip이 길어지면 나오는 스크롤바를 숨김처리하였습니다.
* 이미지 최적화 관련 warring을 제거했습니다. (최적화 했습니다)

iframe 버그 수정, 스크롤바 제거

---

components/Icon/CommentIcon.tsx
components/common/Avatar.tsx
components/common/Portfolio.tsx

main portfolio card

---

next.config.js

백엔드 이미지가 안불러와져서 next.config 에 추가해놓았습니다!

백엔드 이미지 url 추가

---

apis/httpClient.ts
components/app/UploadModal/Form.tsx
components/app/UploadModal/index.tsx
components/common/UserSearchForm.tsx

https://qkrjh0904.atlassian.net/browse/BSSMH-143
컨트리뷰터 잘 나오는 것 확인
참여자 아이디 등록 ui
https://user-images.githubusercontent.com/34783156/221598196-4f512d32-1351-49bf-9845-635189500a20.mp4
참여자 아이디 등록 추가

포트폴리오 업로드 참여자 id 등록 추가

---

components/common/Header/View.tsx
components/main/MainTitle.tsx
config/style.ts
layouts/App.tsx
layouts/ChannelContent.tsx
layouts/Main.tsx
layouts/PortfolioEdit.tsx
layouts/ProfilePage.tsx
layouts/Search.tsx

앱 최대너비 설정 

---

apis/httpClient.ts
pages/portfolio/[portfolioId]/index.tsx

https://qkrjh0904.atlassian.net/browse/BSSMH-160
없음. 
* 조회수 증가 api 추가

조회수 증가 api 추가

---

pages/404.tsx
pages/500.tsx

지라 이슈는 없습니다!
500, 404페이지 디자인 을 반영하였습니다.

404, 500 디자인 반영

---

components/app/Detail.tsx
components/app/PortfolioItem.tsx
components/app/UploadModal/Skills.tsx
components/atoms/Chip.tsx
components/atoms/ChipGroup.tsx
components/atoms/DetailButton.tsx
components/atoms/MemberGroup.tsx
components/common/Portfolio.tsx
package.json
tailwind.config.js
yarn.lock

지라 이슈는 없습니다!
업로드, 수정폼 (업로드 시 크기를 고정하고 ...처리를 하면 어떤 스택인지 구분이 불가능하여 이 방식으로 처리하였습니다.)
포트폴리오 상세 화면
포트폴리오 사이드바 
포트폴리오 메인
포트폴리오 상세 길어질 경우 (멤버 리스트가 찌그러지는 문제가 있어 flex wrap으로 변경하였습니다)
스크린샷 참조 부탁드립니다!

chip 디자인 수정

---

components/portfolio/edit/EditFileUploadView.tsx
components/portfolio/edit/index.tsx
components/profile/ProfileEdit.tsx
layouts/ProfileEdit.tsx

수정 UI 디자인 변경

---

components/common/KebabMenu.tsx
hooks/useOutsideClick.ts

refactor: useOutsideClick 추가

---

pages/profile/[memberId].tsx

https://qkrjh0904.atlassian.net/browse/BSSMH-189
비로그인 유저도 포트폴리오를 조회할 수 있도록 변경하였습니다!
이렇게 작은 기능도 PR로 나누면 좋을지 궁금합니다!

비로그인 포트폴리오 조회 추가

---

components/common/SearchFilter.tsx
types/portfolio.interface.ts

https://qkrjh0904.atlassian.net/browse/BSSMH-187
https://user-images.githubusercontent.com/34783156/226157610-ea8aee8e-c760-4066-b1e2-dbc62a4fca98.mp4
* theme 필터 추가

theme 검색 추가 

---

components/app/PortfolioDetail.tsx
components/app/PortfolioItem.tsx
components/app/UploadModal/Skills.tsx
components/atoms/Chip.tsx
components/atoms/ChipGroup.tsx
components/common/Portfolio.tsx
components/common/Portfolio/SkillList.tsx
components/common/SkillForm.tsx

* ChipGroup 컴포넌트의 Skills 타입 의존성 제거

chipgroup skills 의존성 제거
